name: 'Auto-Merge Action'
description: 'Automatically checks out and merges pull requests from specified repositories with specified labels.'
inputs:
  repositories:
    description: 'JSON string containing repositories and their corresponding labels to process.'
    required: true
    default: '[]'
  path:
    description: 'Path to the repository to merge pull requests into.'
    required: true
    default: '.'
  generate-build-metadata:
    description: 'Whether to generate build metadata.'
    required: false
    default: 'false'
  skip-git-config:
    description: 'Whether to skip setting git user.name and user.email. Defaults to false.'
    required: false
    default: 'false'
  retries:
    description: 'Number of retries for Octokit requests.'
    required: false
    default: '5'
  fetch-retries:
    description: 'Number of retries for git fetch operations.'
    required: false
    default: '5'
runs:
  using: 'node20'
  main: 'dist/index.js'
