name: 'Auto-Merge Action'
description: 'Automatically checks out and merges pull requests from specified repositories with specified labels.'
inputs:
  repositories:
    description: 'JSON string containing repositories and their corresponding labels to process.'
    required: true
    default: '[]'
  path:
    description: 'Path to the repository to merge pull requests into.'
    required: true
    default: '.'

runs:
  using: 'node20'
  main: 'dist/index.js'
